# pull the official base image
FROM node:alpine AS build
# set working direction
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# install application dependencies
COPY Front/package.json ./
COPY Front/package-lock.json ./
RUN npm i
# add app
COPY Front ./
# start app
CMD ["npm", "run", "build"]



FROM nginx:1.21.6-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/conf.d

COPY --from=build /app/public /var/www/