FROM golang:1.18 AS build

ENV GO111MODULE=on \
    GOOS=linux \
    GOARCH=amd64

ARG GO_PROXY
ENV GOPROXY=${GO_PROXY}

RUN mkdir -p /src

# First add modules list to better utilize caching
COPY go.sum go.mod /src/

WORKDIR /src

COPY *.go /src

# Build components.
# Put built binaries and runtime resources in /app dir ready to be copied over or used.
RUN go build .  && \
    mkdir -p /app && \
    cp ./mm-final-project /app/

#
# 2. Runtime Container
#
FROM debian:bullseye-slim

WORKDIR /app

RUN apt update && apt install -y ca-certificates

COPY --from=build /app /app/

CMD ["./mm-fina-project"]
